swagger: '2.0'
info:
  version: '12.2'
  title: Assess Service
  contact:
    name: Start Point Industries
    url: https://www.startpointindustries.com
host: proxy.startpointindustries.com
basePath: /assess/12.2/{deployment}
tags:
  - name: Resources
    description: ' '
paths:
  '/assess':
    post:
      tags:
        - Resources
      summary: Assess
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: deployment
          in: path
          description: deployment
          required: true
          type: string
        - in: body
          name: assessRequest
          description: assessRequest
          required: true
          schema:
            $ref: '#/definitions/AssessRequest'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/AssessResponse'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  '/list-goals':
    get:
      tags:
        - Resources
      summary: List goals
      produces:
        - application/json
      parameters:
        - name: deployment
          in: path
          description: deployment
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ListGoalsResponse'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    post:
      tags:
        - Resources
      summary: List goals
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: deployment
          in: path
          description: deployment
          required: true
          type: string
        - in: body
          name: requestBody
          description: requestBody
          required: true
          schema:
            $ref: '#/definitions/ListGoalsRequest'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ListGoalsResponse'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
definitions:
  AlreadyProvenNodeType:
    type: object
    properties:
      objectType:
        type: string
      id:
        type: string
    title: AlreadyProvenNodeType
  AssessRequest:
    type: object
    properties:
      config:
        $ref: '#/definitions/AssessmentConfiguration'
      globalInstance:
        $ref: '#/definitions/GlobalInstanceType'
    title: AssessRequest
  AssessResponse:
    type: object
    properties:
      events:
        $ref: '#/definitions/ListEventsType'
      globalInstance:
        $ref: '#/definitions/GlobalInstanceType'
      versionInfo:
        $ref: '#/definitions/VersionInfoType'
    title: AssessResponse
  AssessmentConfiguration:
    type: object
    properties:
      outcome:
        $ref: '#/definitions/ResponseOutcome'
      resolveIndecisionRelationships:
        type: boolean
      showEvents:
        type: boolean
      showInvisible:
        type: boolean
      showProperties:
        type: boolean
      showSilent:
        type: boolean
      showVersion:
        type: boolean
    title: AssessmentConfiguration
  AttributeNodeType:
    type: object
    properties:
      objectType:
        type: string
      attributeId:
        type: string
      booleanVal:
        type: boolean
      changePoint:
        type: array
        items:
          $ref: '#/definitions/ChangePoint'
      dateVal:
        type: string
      datetimeVal:
        type: string
      endRelevance:
        type: string
      entityId:
        type: string
      hypotheticalInstance:
        type: boolean
      id:
        type: string
      inferred:
        type: boolean
      instanceId:
        type: string
      nodes:
        type: array
        items:
          anyOf:
            - $ref: '#/definitions/RelationshipNodeType'
            - $ref: '#/definitions/AttributeNodeType'
            - $ref: '#/definitions/AlreadyProvenNodeType'
      numberVal:
        type: number
      properties:
        $ref: '#/definitions/ListCustomPropertiesType'
      startRelevance:
        type: string
      text:
        type: string
      textVal:
        type: string
      timeVal:
        type: string
      type:
        type: string
        enum:
          - BOOLEAN
          - TEXT
          - NUMBER
          - CURRENCY
          - DATE
          - DATETIME
          - TIMEOFDAY
      uncertainVal:
        $ref: '#/definitions/UncertainValue'
      unknownVal:
        $ref: '#/definitions/UnknownValue'
    title: AttributeNodeType
  AttributeType:
    type: object
    properties:
      booleanVal:
        type: boolean
      changePoint:
        type: array
        items:
          $ref: '#/definitions/ChangePoint'
      dateVal:
        type: string
      datetimeVal:
        type: string
      decisionReport:
        $ref: '#/definitions/DecisionReportType'
      id:
        type: string
      inferred:
        type: boolean
      knownOutcomeStyle:
        type: string
        enum:
          - VALUE_ONLY
          - DECISION_REPORT
          - BASE_ATTRIBUTES
      numberVal:
        type: number
      outcomeStyle:
        type: string
        enum:
          - VALUE_ONLY
          - DECISION_REPORT
          - BASE_ATTRIBUTES
      properties:
        $ref: '#/definitions/ListCustomPropertiesType'
      textVal:
        type: string
      timeVal:
        type: string
      type:
        type: string
        enum:
          - BOOLEAN
          - TEXT
          - NUMBER
          - CURRENCY
          - DATE
          - DATETIME
          - TIMEOFDAY
      uncertainVal:
        $ref: '#/definitions/UncertainValue'
      unknownOutcomeStyle:
        type: string
        enum:
          - VALUE_ONLY
          - DECISION_REPORT
          - BASE_ATTRIBUTES
      unknownVal:
        $ref: '#/definitions/UnknownValue'
    title: AttributeType
  ChangePoint:
    type: object
    properties:
      booleanVal:
        type: boolean
      date:
        type: string
      dateVal:
        type: string
      datetimeVal:
        type: string
      numberVal:
        type: number
      textVal:
        type: string
      timeVal:
        type: string
      uncertainVal:
        $ref: '#/definitions/UncertainValue'
      unknownVal:
        $ref: '#/definitions/UnknownValue'
    title: ChangePoint
  CustomPropertyType:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
    title: CustomPropertyType
  DecisionReportType:
    type: object
    properties:
      nodes:
        type: array
        items:
          anyOf:
            - $ref: '#/definitions/RelationshipNodeType'
            - $ref: '#/definitions/AttributeNodeType'
            - $ref: '#/definitions/AlreadyProvenNodeType'
      reportStyle:
        type: string
    title: DecisionReportType
  Entity:
    type: object
    title: Entity
  EntityInstanceType:
    type: object
    properties:
      attribute:
        type: array
        items:
          $ref: '#/definitions/AttributeType'
      entity:
        type: array
        items:
          $ref: '#/definitions/EntityType'
      id:
        type: string
      relationship:
        type: array
        items:
          $ref: '#/definitions/RelationshipType'
    title: EntityInstanceType
  EntityType:
    type: object
    properties:
      id:
        type: string
      inferred:
        type: boolean
      instance:
        type: array
        items:
          $ref: '#/definitions/EntityInstanceType'
      properties:
        $ref: '#/definitions/ListCustomPropertiesType'
    title: EntityType
  GlobalInstanceType:
    type: object
    properties:
      attribute:
        type: array
        items:
          $ref: '#/definitions/AttributeType'
      entity:
        type: array
        items:
          $ref: '#/definitions/EntityType'
      properties:
        $ref: '#/definitions/ListCustomPropertiesType'
      relationship:
        type: array
        items:
          $ref: '#/definitions/RelationshipType'
    title: GlobalInstanceType
  ListCustomPropertiesType:
    type: object
    properties:
      property:
        type: array
        items:
          $ref: '#/definitions/CustomPropertyType'
    title: ListCustomPropertiesType
  ListEventsType:
    type: object
    properties:
      event:
        type: array
        items:
          $ref: '#/definitions/RulebaseEventType'
    title: ListEventsType
  ListGoalsAttributeType:
    type: object
    properties:
      id:
        type: string
      text:
        type: string
      type:
        type: string
        enum:
          - BOOLEAN
          - TEXT
          - NUMBER
          - CURRENCY
          - DATE
          - DATETIME
          - TIMEOFDAY
    title: ListGoalsAttributeType
  ListGoalsEntityType:
    type: object
    properties:
      attribute:
        type: array
        items:
          $ref: '#/definitions/ListGoalsAttributeType'
      entityId:
        type: string
    title: ListGoalsEntityType
  ListGoalsRequest:
    type: object
    properties:
      showVersion:
        type: boolean
    title: ListGoalsRequest
  ListGoalsResponse:
    type: object
    properties:
      entity:
        type: array
        items:
          $ref: '#/definitions/ListGoalsEntityType'
      versionInfo:
        $ref: '#/definitions/VersionInfoType'
    title: ListGoalsResponse
  Parameters:
    type: object
    properties:
      value:
        type: array
        items:
          type: string
    title: Parameters
  QName:
    type: object
    properties:
      localPart:
        type: string
      namespaceURI:
        type: string
      prefix:
        type: string
    title: QName
  RelationshipNodeType:
    type: object
    properties:
      objectType:
        type: string
      endRelevance:
        type: string
      hypotheticalInstance:
        type: boolean
      id:
        type: string
      inferred:
        type: boolean
      nodes:
        type: array
        items:
          anyOf:
            - $ref: '#/definitions/RelationshipNodeType'
            - $ref: '#/definitions/AttributeNodeType'
            - $ref: '#/definitions/AlreadyProvenNodeType'
      properties:
        $ref: '#/definitions/ListCustomPropertiesType'
      relationshipId:
        type: string
      sourceEntityId:
        type: string
      sourceInstanceId:
        type: string
      startRelevance:
        type: string
      state:
        type: string
        enum:
          - KNOWN
          - UNKNOWN
          - UNCERTAIN
      target:
        type: array
        items:
          $ref: '#/definitions/RelationshipTargetType'
      targetEntityId:
        type: string
    title: RelationshipNodeType
  RelationshipTargetType:
    type: object
    properties:
      instanceId:
        type: string
    title: RelationshipTargetType
  RelationshipType:
    type: object
    properties:
      decisionReport:
        $ref: '#/definitions/DecisionReportType'
      id:
        type: string
      inferred:
        type: boolean
      knownOutcomeStyle:
        type: string
        enum:
          - VALUE_ONLY
          - DECISION_REPORT
          - BASE_ATTRIBUTES
      outcomeStyle:
        type: string
        enum:
          - VALUE_ONLY
          - DECISION_REPORT
          - BASE_ATTRIBUTES
      properties:
        $ref: '#/definitions/ListCustomPropertiesType'
      state:
        type: string
        enum:
          - KNOWN
          - UNKNOWN
          - UNCERTAIN
      target:
        type: array
        items:
          $ref: '#/definitions/RelationshipTargetType'
      unknownOutcomeStyle:
        type: string
        enum:
          - VALUE_ONLY
          - DECISION_REPORT
          - BASE_ATTRIBUTES
    title: RelationshipType
  ResponseOutcome:
    type: object
    properties:
      entity:
        type: array
        items:
          $ref: '#/definitions/Entity'
    title: ResponseOutcome
  RulebaseEventType:
    type: object
    properties:
      decisionReport:
        $ref: '#/definitions/DecisionReportType'
      entityId:
        type: string
      instanceId:
        type: string
      message:
        type: string
      name:
        type: string
      parameters:
        $ref: '#/definitions/Parameters'
    title: RulebaseEventType
  UncertainValue:
    type: object
    title: UncertainValue
  UnknownValue:
    type: object
    title: UnknownValue
  VersionInfoType:
    type: object
    properties:
      buildTime:
        type: string
      deploymentVersion:
        type: integer
        format: int32
      policyModelingVersion:
        type: string
      versionUid:
        type: string
    title: VersionInfoType