swagger: '2.0'
info:
  version: '12.0'
  title: Determinations Server
  contact:
    name: Start Point Industries
    url: https://www.startpointindustries.com
host: proxy.startpointindustries.com
basePath: /server/12.0
tags:
  - name: Resources
    description: ' '
paths:
  '/info':
    get:
      tags:
        - Resources
      summary: Get server information
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/GetServerInfoResponse'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  '/rulebases':
    get:
      tags:
        - Resources
      summary: List rulebases
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ListRulebases'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
definitions:
  GetServerInfoResponse:
    type: object
    properties:
      determinationsEngineTimezone:
        type: string
      determinationsEngineVersion:
        type: string
      determinationsServerVersion:
        type: string
      interviewEngineVersion:
        type: string
    title: GetServerInfoResponse
  LanguageListType:
    type: object
    properties:
      language:
        type: array
        items:
          $ref: '#/definitions/LanguageType'
    title: LanguageListType
  LanguageType:
    type: object
    properties:
      name:
        type: string
      value:
        type: string
    title: LanguageType
    xml:
      name: LanguageType
      attribute: false
      wrapped: false
  ListRulebases:
    type: object
    properties:
      rulebase:
        type: array
        items:
          $ref: '#/definitions/Rulebase'
    title: ListRulebases
    xml:
      name: ListRulebases
      attribute: false
      wrapped: false
  Rulebase:
    type: object
    properties:
      availableLanguages:
        $ref: '#/definitions/LanguageListType'
      availableServices:
        $ref: '#/definitions/ServiceListType'
      name:
        type: string
      tz:
        type: string
    title: Rulebase
  ServiceListType:
    type: object
    properties:
      service:
        type: array
        items:
          $ref: '#/definitions/ServiceType'
    title: ServiceListType
  ServiceType:
    type: object
    properties:
      name:
        type: string
      value:
        type: string
    title: ServiceType
